### ISSUE TITLE
Broken in Firefox 69 on OSX

### ISSUE THREAD

**Issue by zmixnyc** [lawfx/YoutubeNonStop#16]
This add-on stopped working in Firefox version 69 on OSX

**Comment by lawfx** [comment]
I will need more info. From all I know, you may be experiencing problems that are produced by YouTube itself. Lately, YouTube has way more bugs than usual.

**Comment by zmixnyc** [comment]
Ok, Good luck..!

**Comment by howaboutsynergy** [comment]
The pop-up does seem to remain in place for me also, sometimes, even after focusing the tab, but the audio is still playing, it's not paused. Personally, I don't mind, as it does the job.

**Comment by lawfx** [comment]
Please check the newest version(v0.7.0). It should fix the popup staying open. 
Btw, @zmixnyc in case there is a misunderstanding, this extension doesn't make the popup not appear at all, it is just supposed to autoclick it so that it doesn't stay open. 
I'll leave this issue open for a week or so if someone wants to add something or if it still doesn't work.
