### ISSUE TITLE
Extension not working when signed in to YouTube (Firefox)

### ISSUE THREAD

**Issue by SheepKid12** [lawfx/YoutubeNonStop#3]
If I'm logged into my YouTube account, the extension fails to work when the "are you still watching?" messages show up. Checking the console reveals `Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.youtube.com/ce6dda2e-df36-458d-8d03-7f3c99a30133 (“default-src”).`, and the messages saying that the extension at least partially worked don't show up. The message in question only appears when logged in for some reason. *Hopefully this made some sense, this was hard for me to describe without sounding stupid.*

If this is the case, then it's not any other extension or JavaScript causing this (yes, I'm the same person who left the 1 star on the firefox addon page, and I did see your feedback), it has to be something else causing it.

**Comment by lawfx** [comment]
Hi, sorry for not getting back to you earlier, I was on a small vacation. I will try to reproduce the bug. In the meantime, can you tell me what version of Firefox are you using? Thanks.

**Comment by SheepKid12** [comment]
Latest beta version of Firefox.

**Comment by lawfx** [comment]
I tried reproducing this, and even had some of my colleagues try the same with no effect. The addon worked in both cases(signed out and signed in). Your error seems to be something related to a Firefox bug, my suggestion would be to avoid beta releases and stick to regular ones, as all things in beta might come with weird stuff attached.

**Comment by tahuyaguy** [comment]
The add-on is working for me, but every video after the first auto pause, I am seeing the same msg as lawfx described above "are you still watching?" and every video pauses after that instead of perhaps only once every 20 minutes. Of course, the addon is still working as designed, however, with every video pausing and then restarting it is more annoying.

If perhaps the addon could also listen for the "are you still watching?" message it would work even better?

I am using Firefox Quantum 64.0 (64-bit) Mozilla Firefox for Ubuntu

**Comment by lawfx** [comment]
@tahuyaguy what you are describing is a known issue but unfortunately I know of no way to fix it. My best guess is that YouTube "knows" that the unpausing didn't occur manually by the user, so it tries to pause the video again, the addon unpauses it again and it's a vicious cycle.
